url: 'http://192.168.0.106/bloc/v2.1'
adminName: Admin_12580_21440704663
adminPassword: '1234'
adminAddress: 31da80648e957aebfc734b6bdc22f5e67cb19033
AdminInterface:
  address: feb3252e5b8d8c366f1c68566a3d65f58f8af9e5
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
