url: 'http://192.168.0.106/bloc'
adminName: Admin_58635_9739635779
adminPassword: '1234'
AdminInterface:
  address: c6264a453d05a1fad016198c11bcb73047bcf72c
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
