url: 'http://192.168.0.106/bloc'
adminName: Admin_69746_11961147617
adminPassword: '1234'
AdminInterface:
  address: e9c3d43050a79f6367c231d0cf5296dda82200b5
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
