url: 'http://192.168.0.106/bloc'
adminName: Admin_64955_11028595158
adminPassword: '1234'
AdminInterface:
  address: d2600a7b79cfcba968f91fa35d6425c03d2f50dc
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
