url: 'http://192.168.0.106/bloc'
adminName: Admin_82401_14795461928
adminPassword: '1234'
adminAddress: f1fb92767bc996a084d5e779919d4c4f6bc1c4e7
AdminInterface:
  address: a614901d0ac239c84a792caee5263645ad28fe97
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
