url: 'http://192.168.0.106/bloc'
adminName: Admin_61826_10251644033
adminPassword: '1234'
AdminInterface:
  address: f7610f758e79cc412f4e131f02e5aaddb871398c
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
