url: 'http://192.168.0.106/bloc'
adminName: Admin_58762_9754793386
adminPassword: '1234'
AdminInterface:
  address: 2244e1b1c6b272eaa29c3f39a350f55e30aec96d
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
