url: 'http://192.168.0.106/bloc'
adminName: Admin_61607_10208523270
adminPassword: '1234'
AdminInterface:
  address: 88afda8f02390b670a07bd58aa039e8c3ef7c006
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
