url: 'http://bayar6.eastus.cloudapp.azure.com/bloc/'
adminName: Admin_12240_20159897986
adminPassword: '1234'
adminAddress: 763cfa33a455ed8c6efc5f2627118fdb5d482869
AdminInterface:
  address: d92d8f16bebb20e3050284849f0313d00151f23d
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
