apiDebug: false
password: '1234'
timeout: 600000
libPath: ./server/lib
dataFilename: ./server/dapp/dapp.presets.yaml
deployFilename: ./server/config/192.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://bayar6.eastus.cloudapp.azure.com:9000'
    stratoUrl: 'http://bayar6.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://bayar6.eastus.cloudapp.azure.com/bloc/v2.1'
    searchUrl: 'http://bayar6.eastus.cloudapp.azure.com/cirrus'
