url: 'http://localhost/bloc/v2.1'
adminName: Admin_56292_1368469542
adminPassword: '1234'
adminAddress: bc20cec3f3ff0cedaf0d4f10e9a8c9b0b0c53228
AdminInterface:
  address: 70664272d3bf89cfd96e13d775961e9c2a7d575d
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
