url: 'http://localhost/bloc/v2.1'
adminName: Admin_87798_996933377
adminPassword: '1234'
adminAddress: db1f0e01204ea74ab30cb1a03968810a6667ef5d
AdminInterface:
  address: 8304bd7a23821d3e1bf53df596f0a68b92adc0a3
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
