apiDebug: true
password: '1234'
timeout: 600000
libPath: ./server/lib
contractsPath: ./contracts/
dataFilename: ./server/dapp/dapp.presets.yaml
deployFilename: ./server/config/p2p.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: 'http://p2pnode3.eastus.cloudapp.azure.com:9000'
    stratoUrl: 'http://p2pnode3.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://p2pnode3.eastus.cloudapp.azure.com/bloc'
    searchUrl: 'http://p2pnode3.eastus.cloudapp.azure.com/cirrus'
