url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_75545_17839185848
adminPassword: '1234'
AdminInterface:
  address: a5ec77da1818de623e04701505efba543a6493bf
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
