url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_88988_18607895100
adminPassword: '1234'
adminAddress: 6df2cdee6fd461f7474d1a34284ee13dea0e2444
AdminInterface:
  address: 8ab17c433ecf65b9f5ff13b4661cff0956ce911e
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
