url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_11907_20133774049
adminPassword: '1234'
adminAddress: 7cad3ff7feccc75c117acf5624a920c156f8344e
AdminInterface:
  address: 85dfb0a237797592e104c349ca2c801771d10f63
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
