url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_76895_17848053853
adminPassword: '1234'
AdminInterface:
  address: 94fda5bb1a20d41e84051aaa8aa9f4e40ee3faf7
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
