url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_74249_17802331812
adminPassword: '1234'
AdminInterface:
  address: 2140cde33a15710f1aaf07ad23c88948fe8232e2
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
