url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_96055_18975528811
adminPassword: '1234'
adminAddress: 43d40c3ba4281771117261b0a65a62fd0958c4a1
AdminInterface:
  address: 1fbc32638bfd7c4d2596f98c77144e6707958fe1
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
