url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_11437_20106291980
adminPassword: '1234'
adminAddress: 48986d3c50168b23c6c842a752d12542fc03f34c
AdminInterface:
  address: 6f97eb829ad0ca631e1fd6f92ad8199af2c03c12
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
