url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_13366_1529348357
adminPassword: '1234'
adminAddress: 8e9f55ccd8b37b13fc49ec688ef669d238815756
AdminInterface:
  address: 9ad6e602b39fc55b4c0d6ea955c34abd9fbb3fac
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
