url: 'http://strato-int.centralus.cloudapp.azure.com/bloc/'
adminName: Admin_22700_4429791369
adminPassword: '1234'
AdminInterface:
  address: 822b8023322e3847026f3414e6a7c1677dd7820b
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
