url: 'http://tester14.eastus.cloudapp.azure.com/bloc/'
adminName: Admin_17444_20561141112
adminPassword: '1234'
adminAddress: 5d3222ed2e28c92d32abda7b956646a36e709a33
AdminInterface:
  address: 16a75cb50c475b3c61e2165053c19501cb21854e
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
