url: 'http://tester14.eastus.cloudapp.azure.com/bloc/'
adminName: Admin_16205_20479062115
adminPassword: '1234'
adminAddress: 025f6964de7b516150fe595c14245878165c39a9
AdminInterface:
  address: 0b0074006479d0d814ed6d9856bd327d7b091225
users:
  - username: Supplier1
    password: '1234'
    role: SUPPLIER
  - username: Supplier2
    password: '1234'
    role: SUPPLIER
  - username: Buyer1
    password: '1234'
    role: BUYER
  - username: Buyer2
    password: '1234'
    role: BUYER
